name: Java Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v3.10.0
      with:
        java-version: 11
        java-package: jdk

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
