trigger:
- develop

pool: 'IMT Servers'

steps:
- task: Maven@3
  displayName: "Clean pom.xml"
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean'
    mavenDirectory: $(mavenDirectory)

- task: Maven@3
  displayName: "Compile pom.xml"
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'compile'
    mavenDirectory: $(mavenDirectory)

- task: Maven@3
  displayName: "Install pom.xml"
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    mavenDirectory: $(mavenDirectory)

- task: Maven@3
  displayName: "Deploy pom.xml"
  condition: ne(variables['Build.Reason'], 'PullRequest')
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'deploy'
    mavenDirectory: $(mavenDirectory)
