name: Java Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v3.10.0
      with:
        java-version: 11
        distribution: adopt
        java-package: jdk
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
       name: my-artifact
       path: path/to/my/artifact
