name: Maven Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clean pom.xml
        run: mvn clean
      - name: Compile pom.xml
        run: mvn compile
      - name: Install pom.xml
        run: mvn install
      - name: Deploy pom.xml
        if: ${{ github.event_name != 'pull_request' }}
        run: mvn deploy
